services:
  app:
    image: "mcr.microsoft.com/devcontainers/go:1-1.22-bookworm"
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - ../data:/workspace/data
    command: sleep infinity
